name: cashflow
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"
  
dependencies:
  get: 4.6.6
  flutter:
    sdk: flutter
  reactive_forms: 16.1.1
  http: 1.1.0
  origami:
    path: ../origami
  amplify_flutter: ^1.0.0
  amplify_auth_cognito: ^1.0.0
  amplify_authenticator: ^1.0.0
  amplify_api: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
flutter:
  uses-material-design: true

  assets:
    - assets/emptyBox.png
    - assets/http400x.png
    - assets/baseLoading.png
    - assets/loading.png

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter/static/Inter-Black.ttf
        - asset: fonts/Inter/static/Inter-Bold.ttf
        - asset: fonts/Inter/static/Inter-ExtraBold.ttf
        - asset: fonts/Inter/static/Inter-ExtraLight.ttf
        - asset: fonts/Inter/static/Inter-Light.ttf
        - asset: fonts/Inter/static/Inter-Medium.ttf
        - asset: fonts/Inter/static/Inter-Regular.ttf
        - asset: fonts/Inter/static/Inter-SemiBold.ttf
        - asset: fonts/Inter/static/Inter-Thin.ttf
          style: italic